### ISSUE TITLE
Ban Adobe Analytics

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [Emano-Waldeck/Opt-Out#5]
[Adobe Analytics](https://business.adobe.com/products/adobe-analytics.html) is yet another online analytic service by Adobe Inc. If you can add new codes to ban this API, anyone who wish himself/herself out of Adobe Analytics will get benefits from your extension.

**Comment by KrasnayaPloshchad** [comment]
Maybe [Product Analytics](https://business.adobe.com/products/adobe-analytics/product-analytics.html) could be banned as well.

**Comment by Emano-Waldeck** [comment]
As far as I can say there is no opt-out preference that we can use. The only solution is to block the network request.

**Comment by KrasnayaPloshchad** [comment]
Oh yeah, block its network request would be nice choice, I hope to see your update soon.
